version: "3.8"

services:
  coredns-sync:
    image: ghcr.io/StevenC4/docker-coredns-sync:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock